fork = true
frame = "full"
idle = true
maximized = false
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
mouse-cursor-icon = "arrow"
title-hidden = true
vsync = true
wsl = false

[font]
normal = [
  "SauceCodePro Nerd Font Mono",
] # Will use the bundled Fira Code Nerd Font by default
size = 13
