gui:
  theme:
    # Border color of focused window
    activeBorderColor:
      # - bold
      - "#B14242"
      # - red

    # Border color of non-focused windows
    inactiveBorderColor:
      - "#a7a7a7"

    # Border color of focused window when searching in that window
    searchingActiveBorderColor:
      - "#4A8B8B"
      - bold

    # Color of keybindings help text in the bottom line
    optionsTextColor:
      - "#B14242"

    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - "#323232"

    # Background color of selected line when view doesn't have focus.
    inactiveViewSelectedLineBgColor:
      - bold

    # Foreground color of copied commit
    cherryPickedCommitFgColor:
      - "#E5A72A"

    # Background color of copied commit
    cherryPickedCommitBgColor:
      - "#121212"

    # Foreground color of marked base commit (for rebase)
    markedBaseCommitFgColor:
      - "#d5d5d5"

    # Background color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - yellow

    # Color for file with unstaged changes
    unstagedChangesColor:
      - red

    # Default text color
    defaultFgColor:
      - "#d5d5d5"
