# [manager]
# prepend_keymap = [{ on = "<C-n>", run = '''
#   shell 'dragon-drop -x -i -T "$1"' --confirm
# ''' }]

[[manager.prepend_keymap]]
on = "!"
run = 'shell --block --interactive'
desc = "Open shell here"
[[manager.prepend_keymap]]
on = "<C-n>"
run = '''
shell 'dragon-drop -x -i -T "$1"' --confirm
'''
desc = "Drag and drop selection"
