# [MODIFIER+]<CHAR|NAMED_KEY>
# where:
#   MODIFIER: Shift|Alt|Ctrl
#   CHAR: Any printable character
#   NAMED_KEY: Enter|Space|Tab|Backspace|Esc|Left|Right|Up|Down
#     |Ins|Del|Home|End|PageUp|PageDown|PauseBreak|NumpadCenter
#     |F0|F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12
# "Shift+i" = "seek +10s"

[keybindings]
"m" = "move left"
"n" = "move down"
"e" = "move up"
"i" = "move right"
"Ctrl+q" = "quit"
"Ctrl+u" = "move up 5"
"Ctrl+d" = "move down 5"
"Shift+n" = "shift down"
"Shift+e" = "shift up"
"Shift+m" = "seek +10s"
"Shift+i" = "seek -10s"
"Ctrl+n" = "voldown 1"
"Ctrl+e" = "volup 1"
"Shift+q" = "queue; move down 1"
"q" = "focus queue"
# "s" = "focus search"
"l" = "focus library"
"space" = "playpause"
"Shift+r" = "similar current"
