# general
background = '#121212'
border_fg = '#737373'
text_fg = '#b4b4b4'
dimmed_text_fg = '#949494'
# input
input_text_fg = '#b4b4b4'
result_count_fg = '#4A8B8B'
# results
result_name_fg = '#a7a7a7'
result_line_number_fg = '#f9e2af'
result_value_fg = '#b4befe'
selection_fg = '#d5d5d5'
selection_bg = '#323232'
match_fg = '#f38ba8'
# preview
preview_title_fg = '#fab387'
# modes
channel_mode_fg = '#f5c2e7'
remote_control_mode_fg = '#a6e3a1'
send_to_channel_mode_fg = '#89dceb'
