theme = "ashen"

[editor]
line-number = "relative"
# Not sure if I should enable this by default...
# maybe it's better to just get used to using the clipboards separately?
# Wouldn't be a bad idea to encorporate two clipboards into my workflow,
# especially for stuff like swapping selections and stuff...
# default-yank-register = '+'
cursorline = true
bufferline = "multiple"
color-modes = true
scrolloff = 2
jump-label-alphabet = "tnseriplfuwydhcxoaqz"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NRM"

[keys.normal]
m = "move_char_left"
M = "goto_line_start"
n = "move_visual_line_down"
e = "move_visual_line_up"
i = "move_char_right"
I = "goto_line_end"
h = "insert_mode"
H = "insert_at_line_start"
w = "move_next_sub_word_start"
b = "move_prev_sub_word_start"
l = "move_next_sub_word_end"
L = "move_next_long_word_end"
k = "search_next"
K = "search_prev"
C-q = ":qa"
C-Q = ":qa!"
C-m = "jump_view_left"
C-M = ":bp"
C-n = "jump_view_down"
C-e = "jump_view_up"
C-i = "jump_view_right"
C-I = ":bn"
"S-left" = ":bp"
"S-right" = ":bn"

[keys.select]
m = "extend_char_left"
M = "extend_to_line_start"
n = "extend_visual_line_down"
e = "extend_visual_line_up"
i = "extend_char_right"
I = "extend_to_line_end"
k = "extend_search_next"
K = "extend_search_prev"
j = "extend_next_sub_word_end"
J = "extend_next_long_word_end"
[keys.normal.j]
m = "match_brackets"
j = "match_brackets"
s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"
[keys.normal."C-w"]
m = "jump_view_left"
C-m = "jump_view_left"
n = "jump_view_down"
C-n = "jump_view_down"
i = "jump_view_right"
C-i = "jump_view_right"
e= "jump_view_up"
C-e = "jump_view_up"
M = "swap_view_left"
N = "swap_view_down"
E = "swap_view_up"
I = "swap_view_right"
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
H = "no_op"
J = "no_op"
K = "no_op"
L = "no_op"
