theme = "onedark"

[editor]
line-number = "relative"
default-yank-register = '+'
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
m = "move_char_left"
M = "goto_line_start"
n = "move_visual_line_down"
e = "move_visual_line_up"
i = "move_char_right"
I = "goto_line_end"
h = "insert_mode"
H = "insert_at_line_start"
w = "move_next_sub_word_start"
b = "move_prev_sub_word_start"
j = "move_next_sub_word_end"
J = "move_next_long_word_end"
k = "search_next"
K = "search_prev"

[keys.select]
m = "extend_char_left"
M = "extend_to_line_start"
n = "extend_visual_line_down"
e = "extend_visual_line_up"
i = "extend_char_right"
I = "extend_to_line_end"
k = "extend_search_next"
K = "extend_search_prev"

[keys.normal.l]
m = "match_brackets"
l = "match_brackets"
s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"

[keys.normal."C-w"]
m = "jump_view_left"
C-m = "jump_view_left"
