theme = "onedark"

[editor]
line-number = "relative"
default-yank-register = '+'
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
# A comment...
# m n e i
# M match mode
# N search occurrence
# E end of word
# I insert mode
# h j k l
# H
# L
# J
# K

