theme = "onedark"

[editor]
line-number = "relative"
default-yank-register = '+'
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
