[language-server.lua-language-server.config.Lua]
workspace.library = [
  "/usr/share/nvim/runtime/lua",
  "/home/fic/.config/nvim/lua",
]

[[language]]
name = "toml"
roots = ["."]

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true
