[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
# Config example
# [language-server.harper-ls.config.harper-ls]
# diagnosticSeverity = "warning"

[language-server.lua-language-server.config.Lua]
workspace.library = [
  "/usr/share/nvim/runtime/lua",
  "/home/fic/.config/nvim/lua",
]

[language-server.tinymist]
command = "tinymist"
[language-server.tinymist.config]
exportPdf = "onType"
# exportPdf = "onSave"
outputPath = "$root/target/$dir/$name"
formatterMode = "typstyle"

[[language]]
name = "typst"
auto-format = true
language-servers = ["tinymist", "harper-ls"]

[language-server.buffer-language-server]
command = "buffer-language-server"

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100           # set max completion results len for each group: words, snippets, unicode-input
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

# write logs to /tmp/completion.log
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

[[language]]
name = "toml"
roots = ["."]
language-servers = ["taplo", "scls"]
auto-format = true

[language-server.iwe]
command = "iwes"

[[language]]
name = "markdown"
# language-servers = ["iwe", "scls"]
# language-servers = ["marksman", "markdown-oxide", "scls"]
# language-servers = ["markdown-oxide", "scls"]
# language-servers = ["marksman", "markdown-oxide", "buffer-language-server"]
# language-servers = ["iwe", "scls"]
# language-servers = ["marksman", "iwe", "scls"]
language-servers = ["harper-ls", "marksman", "scls"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true


[[language]]
name = "stub"
scope = "text.stub"
file-types = []
shebangs = []
roots = []
auto-format = false
language-servers = ["scls"]


[language-server.texlab.config.texlab.build]
onSave = true

[[language]]
name = "mail"
scope = "text.mail"
file-types = ["eml"]
# injection-regex = "mail|eml|email"

[[grammar]]
name = "mail"
source.path = "/home/fic/dev/tree-sitter-mail"
# source = { git = "https://github.com/stevenxxiu/tree-sitter-mail", rev = "e3d63ac2093e22777cb30d70b9264f48814622ad" }

[[language]]
name = "test"
scope = "source.test"
file-types = [{ glob = "test/corpus/*.txt" }]

[[grammar]]
name = "test"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-test", rev = "93746e2e387ae757d21088ab0ab5657efffb973e" }
